# Generated by Django 2.0.2 on 2018-04-19 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20180419_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaries',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterField(
            model_name='commentaries',
            name='comment_date',
            field=models.DateTimeField(auto_created=True, blank=True, default=datetime.datetime(2018, 4, 19, 12, 49, 27, 31911)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='post_date',
            field=models.DateTimeField(auto_created=True, blank=True, default=datetime.datetime(2018, 4, 19, 12, 49, 27, 31911)),
        ),
    ]
