# Generated by Django 2.0.2 on 2018-04-19 09:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_auto_20180419_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaries',
            name='comment_date',
            field=models.DateTimeField(auto_created=True, blank=True, default=datetime.datetime(2018, 4, 19, 12, 55, 48, 542755)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='post_date',
            field=models.DateTimeField(auto_created=True, blank=True, default=datetime.datetime(2018, 4, 19, 12, 55, 48, 542755)),
        ),
    ]
