# Generated by Django 2.0.2 on 2018-04-19 14:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_auto_20180419_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaries',
            name='comment',
        ),
        migrations.AddField(
            model_name='commentaries',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='landing.Messages'),
        ),
        migrations.AlterField(
            model_name='commentaries',
            name='comment_date',
            field=models.DateTimeField(auto_created=True, blank=True, default=datetime.datetime(2018, 4, 19, 17, 47, 34, 88635)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='post_date',
            field=models.DateTimeField(auto_created=True, blank=True, default=datetime.datetime(2018, 4, 19, 17, 47, 34, 88635)),
        ),
    ]
