# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-22 07:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_auto_20180419_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaries',
            options={'ordering': ['comment_date'], 'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['post_date'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AlterField(
            model_name='commentaries',
            name='comment_date',
            field=models.DateTimeField(auto_created=True, blank=True, default=datetime.datetime(2018, 4, 22, 10, 1, 48, 534976)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='post_date',
            field=models.DateTimeField(auto_created=True, blank=True, default=datetime.datetime(2018, 4, 22, 10, 1, 48, 534000)),
        ),
    ]
