# Generated by Django 2.0.4 on 2018-04-23 12:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0012_auto_20180423_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaries',
            name='comment_date',
            field=models.DateTimeField(auto_created=True, blank=True, default=datetime.datetime(2018, 4, 23, 12, 56, 58, 165593, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='messages',
            name='post_date',
            field=models.DateTimeField(auto_created=True, blank=True, default=datetime.datetime(2018, 4, 23, 12, 56, 58, 164608, tzinfo=utc)),
        ),
    ]
